import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          DEFAULT: "#15803d",
          hover: "#166534",
          light: "#f0fdf4",
          subtle: "#f0fdf4",
          border: "#bbf7d0",
        },
        primary: {
          DEFAULT: "#00652c",
          container: "#15803d",
          fixed: "#95f8a7",
          "fixed-dim": "#79db8d",
        },
        "on-primary": "#ffffff",
        "on-primary-container": "#d3ffd5",
        "on-primary-fixed": "#00210a",
        secondary: {
          DEFAULT: "#006c49",
          container: "#6cf8bb",
          fixed: "#6ffbbe",
          "fixed-dim": "#4edea3",
        },
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00714d",
        tertiary: {
          DEFAULT: "#854600",
          container: "#a95b00",
          fixed: "#ffdcc3",
          "fixed-dim": "#ffb77d",
        },
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fff1e9",
        surface: {
          DEFAULT: "#f9f9ff",
          dim: "#cfdaf2",
          bright: "#f9f9ff",
          container: "#e7eeff",
          "container-lowest": "#ffffff",
          "container-low": "#f0f3ff",
          "container-high": "#dee8ff",
          "container-highest": "#d8e3fb",
          variant: "#d8e3fb",
        },
        "on-surface": "#111c2d",
        "on-surface-variant": "#3f493f",
        outline: "#6f7a6e",
        "outline-variant": "#becabc",
        error: {
          DEFAULT: "#ba1a1a",
          container: "#ffdad6",
        },
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        display: ["var(--font-jakarta)", "Plus Jakarta Sans", "Inter", "sans-serif"],
        "headline-xl": ["var(--font-jakarta)", "Plus Jakarta Sans"],
        "headline-lg": ["var(--font-jakarta)", "Plus Jakarta Sans"],
        "headline-md": ["var(--font-jakarta)", "Plus Jakarta Sans"],
        "headline-sm": ["var(--font-jakarta)", "Plus Jakarta Sans"],
        "title-md": ["var(--font-inter)", "Inter"],
        "body-lg": ["var(--font-inter)", "Inter"],
        "body-md": ["var(--font-inter)", "Inter"],
        "body-sm": ["var(--font-inter)", "Inter"],
        "label-lg": ["var(--font-inter)", "Inter"],
        "label-md": ["var(--font-inter)", "Inter"],
        "label-sm": ["var(--font-inter)", "Inter"],
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.375rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        margin: "1rem",
        gutter: "1rem",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
